---
http_interactions:
- request:
    method: get
    uri: https://api.kissmetrics.com/core/products/8d637290-a04f-0132-83a0-22000ab4dcd7/metrics
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      User-Agent:
      - KISSmetrics-ruby 0.0.1
      Content-Type:
      - application/json; charset=UTF-8
      Authorization:
      - Bearer g69tAwVa2PXJS5KBzz5lWKgBkAzERYIR9XGoS2VkWUz4vnT_qZVIW6ehkPjIGmga
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 404
      message: Not Found
    headers:
      Cache-Control:
      - no-cache
      Content-Type:
      - application/json; charset=utf-8
      Date:
      - Fri, 27 Feb 2015 03:50:58 GMT
      Server:
      - nginx/1.6.2
      Status:
      - 404 Not Found
      Vary:
      - Accept-Encoding
      X-Request-Id:
      - d050d563-b978-4c14-8306-8d6f6c3f8fb3
      X-Runtime:
      - '0.049637'
      Content-Length:
      - '86'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"meta":{"status":404,"message":"not found","errors":["not_found"]}}'
    http_version: 
  recorded_at: Fri, 27 Feb 2015 03:50:58 GMT
recorded_with: VCR 2.9.3
